<?php


function events_module_theme($existing, $type, $theme, $path)
{
  return [
    'events' => [
      'variables' => [
        'events' => NULL,
      ],
      'template' => 'events',
    ],
    'event_card' => [
      'variables' => [
        'event' => NULL,
      ],
      'template' => 'event_card',
    ],
    'event_details' => [
      'variables' => [
        'event' => NULL,
      ],
      'template' => 'event_details',
    ],
  ];
}
